url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Almacenes Juanma
email: almacenes.juanma@gmail.com
description: 
    Almacén de materiales Juan Manuel Frutos S.L.
baseurl: ""
url: "https://jorfru.github.io/AlmacenesJuanmaWebpage/" 
twitter_username: UC3Music
github_username:  uc3music
mailing_list: https://groups.google.com/forum/#!forum/uc3music-e

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4e8bb8
  secondary: 2c6099  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Azulejos
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Pavimentos
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Baños
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Cocinas
  pic: 4
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Camiones
camion:
- name: Camiones
  pic: 1
  position: Transportes y servicios de grúa
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Maquinaria
  pic: 2
  position: Movimiento de tierra
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Contenedores
  pic: 3
  position: Retirada de escombros
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ALMACENES-JUANMA-materiales-de-construccion-130872176936754/?fref=ts
  - title: envelope
    url : mailto:almacenes.juanma@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Crta. Miraflores a Guadalix M-626 P.K. 6.
  - line: 28792 Miraflores de la Sierra (Madrid)
  - line: 91 844 52 88
  - line: almacenes.juanma@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

